### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by safrazik** [safrazik/vue-file-agent#22]
- [x] Clean up css: break by features
- [ ] Clean up css: fix class names
- [x] Convert codebase to ES6+ or TypeScript
- [ ] Extraction Stage 1: Externalize functionalities from Vue Components.
- [ ] Extraction Stage 2: Compose Vue Component with a generalized handler
- [ ] Write unit tests for externalized functionalities

**Comment by safrazik** [comment]
(v 1.5+) Codebase refactored to TypeScript

**Comment by boumediane10** [comment]
I'm getting this error when I use the component

app.js:32091 [Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VueFileAgent>
       <ImageUploader> at resources/js/components/ImageUploader.vue
         <ProductsCreate> at resources/js/components/ProductsCreate.vue
           <App> at resources/js/components/App.vue
             <Root>

**Comment by safrazik** [comment]
Can you paste the code of `ImageUploader.vue` component?

Please create new issue instead of commenting on existing issue.

**Comment by boumediane10** [comment]
It's just a demo

```
<template>

    <div>
        <VueFileAgent :uploadUrl="uploadUrl" v-model="filesData"></VueFileAgent>
    </div>

</template>

<script>
  import VueFileAgent from 'vue-file-agent';
  export default {
    components: {
            VueFileAgent
        },
    data: function () {
      return {
        // ...
        filesData: [],
        uploadUrl: 'https://example.com',
        // ...
      };
    },
    // ...
  };
</script>
```

**Comment by safrazik** [comment]
```javascript
import VueFileAgent from 'vue-file-agent';
```
When you import like this, the default export you get is not the `VueFileAgent` component. Please use the following example

```javascript
  import VueFileAgentPlugin from 'vue-file-agent';
  const VueFileAgent = VueFileAgentPlugin.VueFileAgent;
  export default {
    components: {
            VueFileAgent
        },
    // ...
  };
  // ...
```

Have a look at [here](https://github.com/safrazik/vue-file-agent/blob/master/src/index.ts) for the available.

Looks like I need a proper way to export these components. Thanks for bringing this up @boumediane10

**Comment by boumediane10** [comment]
Thanks mate it works

Now I got this error

```
vue-file-icon.vue?22fe:13 Uncaught TypeError: Cannot read property 'extend' of undefined
    at Module.fb15 (vue-file-icon.vue?22fe:13)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
    at webpackUniversalModuleDefinition (universalModuleDefinition:9)
    at universalModuleDefinition:10
```

I believe it's due to jQuery import?

**Comment by safrazik** [comment]
No, the library doesn't depend on any external libraries (except, Vue js, obviously)
The propblem is, there are some other internal components used by the `VueFileAgent` component.
```javascript
    Vue.component('VueFileIcon', VueFileIcon);
    Vue.component('VueFilePreview', VueFilePreview);
    Vue.component('VueFileList', VueFileList);
    Vue.component('VueFileListItem', VueFileListItem);
    Vue.component('VueFileAgent', VueFileAgent);
```
Again, you can find them [here](https://github.com/safrazik/vue-file-agent/blob/master/src/index.ts)

So I highly recommend you registering the plugin itself like in the [Official Docs](https://safrazik.github.io/vue-file-agent/#installation):

```javascript
import Vue from 'vue';
import VueFileAgentPlugin from 'vue-file-agent';
import VueFileAgentStyles from 'vue-file-agent/dist/vue-file-agent.css';

Vue.use(VueFileAgentPlugin);
```
This way you can use the component anywhere you want.

**Comment by boumediane10** [comment]
I just did but I still get the same error

`Uncaught TypeError: Cannot read property 'extend' of undefined`

**Comment by safrazik** [comment]
Is there anyway I can reproduce the issue? Are you using the `1.5.2` version? (Please don't use `1.5.3-beta` version yet)

**Comment by boumediane10** [comment]
I just run `npm install vue-file-agent --save` I have no idea how to use the previous version kinda newbie in this vue stuff

**Comment by boumediane10** [comment]
I just installed the `1.5.2 ` version and still same error

```
    "dependencies": {
        "install": "^0.13.0",
        "npm": "^6.13.6",
        "vue-file-agent": "^1.5.2",
        "vue-toastr": "^2.1.2"
    }
```

**Comment by safrazik** [comment]
You can install a particular version of npm package like this:
```
npm install vue-file-agent@1.5.2 --save
```
But your issue looks strange. I won't be able to help you if I cannot reproduce your issue. I'm sorry. You can use [CodeSandbox](https://codesandbox.io/) to create a similar environment like your local environment and share it.

**Comment by safrazik** [comment]
Closing to avoid confusion
